Layout/EmptyLines:
  Exclude:
    - Gemfile
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
